---
settings:
  name: ONTAP FlexArray
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: ONTAP FlexArray Dokumente
    url: "/index.html"
  - section: implement-e-series
  - section: implement-third-party
  - section: install
  - title: Rechtliche Hinweise
    url: "/reference_legal_notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
