---
permalink: install/concept_how_the_array_lun_name_is_displayed_in_ontap.html 
sidebar: sidebar 
keywords: how, array, lun, name, displayed, ontap, output, example, storage, disk 
summary: Jeder Array-LUN wird ein eindeutiger Cluster-weiter Name zugewiesen, obwohl mehrere Pfade zur Array-LUN vorhanden sind. Dies unterscheidet sich von früheren Versionen, bei denen jede Array-LUN mehrere Namen hatte, basierend auf dem Pfad, der zu einem bestimmten Zeitpunkt auf die LUN zugreift. 
---
= Wie der Array-LUN-Name in ONTAP angezeigt wird
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Jeder Array-LUN wird ein eindeutiger Cluster-weiter Name zugewiesen, obwohl mehrere Pfade zur Array-LUN vorhanden sind. Dies unterscheidet sich von früheren Versionen, bei denen jede Array-LUN mehrere Namen hatte, basierend auf dem Pfad, der zu einem bestimmten Zeitpunkt auf die LUN zugreift.

Sie können die alten Namen, die den einzelnen Array-LUNs zugeordnet sind, anzeigen, indem Sie den Befehl ausführen `storage disk show --disk <disk name> -fields diskpathnames` .



== Ausgabebeispiel für den Befehl Storage Disk show --Disk <disk name> -fields diskpathnames

[listing]
----
vgv3270f47ab::*> storage disk show -type LUN
                     Usable           Disk    Container   Container
Disk                   Size Shelf Bay Type    Type        Name      Owner
---------------- ---------- ----- --- ------- ----------- --------- --------
EMC-1.7              8.66GB     -   - LUN     spare       Pool0     vgv3270f47a
EMC-1.8              8.66GB     -   - LUN     spare       Pool0     vgv3270f47a
EMC-1.9              8.66GB     -   - LUN     spare       Pool0     vgv3270f47a
EMC-1.10             8.66GB     -   - LUN     spare       Pool0     vgv3270f47a

vgv3270f47ab::*> storage disk show -disk EMC-1.10 -fields diskpathnames
disk     diskpathnames
-------- -------------------------------------------------------------------------------------------------------------------------------
EMC-1.10 vgv3270f47a:vgbr300s181:5.126L9,vgv3270f47a:vgbr300s139:5.126L9,vgv3270f47b:vgbr300s181:5.126L9,vgv3270f47b:vgbr300s139:5.126L9
----