---
permalink: install/concept_using_lun_groups_to_partition_the_load_over_v_series_connections.html 
sidebar: sidebar 
keywords: benefits, use, multiple, lun, groups 
summary: Sie können in Ihrer Storage-Konfiguration mehrere LUN-Gruppen verwenden, um zusätzliche Kapazität zu erhalten und die System-Performance zu verbessern, indem Sie den Workload auf mehr Ziel-Ports verteilen. 
---
= Vorteile durch die Verwendung mehrerer LUN-Gruppen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können in Ihrer Storage-Konfiguration mehrere LUN-Gruppen verwenden, um zusätzliche Kapazität zu erhalten und die System-Performance zu verbessern, indem Sie den Workload auf mehr Ziel-Ports verteilen.

Eine _LUN-Gruppe_ ist ein Satz logischer Geräte auf dem Speicher-Array, auf die ein ONTAP-System über dieselben Pfade zugreift. Der Speicher-Array-Administrator konfiguriert eine Gruppe logischer Geräte als Gruppe, um festzulegen, welche Host-WWPNs auf sie zugreifen können. ONTAP bezeichnet diesen Satz von Geräten als _LUN-Gruppe_.

Die Verwendung mehrerer LUN-Gruppen bietet folgende Vorteile:

* Es gibt Beschränkungen in Bezug auf die Anzahl der LUNs, die ein bestimmtes FC-Initiator-Port-Paar unterstützen kann.
+
Insbesondere bei großen Speicher-Arrays kann die erforderliche Kapazität die Kapazität übersteigen, die eine einzelne LUN-Gruppe bieten kann. Daher kann die Verwendung mehrerer LUN-Gruppen von Vorteil sein.

* Sie können die Last von Array-LUNs über die FC-Initiator-Port-Paare partitionieren.


[NOTE]
====
Die Verwendung mehrerer LUN-Gruppen wird nicht für alle Speicher-Arrays unterstützt. Prüfen Sie in der _Interoperability Matrix_, ob eine Konfiguration mit mehreren LUN-Gruppen für Ihr Speicher-Array unterstützt wird.

====
*Verwandte Informationen*

https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"]
