---
permalink: install/reference_the_storage_errors_show_messages_and_their_resolution.html 
sidebar: sidebar 
keywords: storage, errors, show, messages, resolution 
summary: Wenn Speicherfehler einen Fehlerzustand anzeigen, müssen Sie ermitteln, warum der Fehler aufgetreten ist und wie er behoben werden kann. 
---
= Die Speicherfehler zeigen Meldungen und deren Auflösung an
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn `storage errors show` ein Fehlerzustand markiert wird, müssen Sie feststellen, warum der Fehler aufgetreten ist und wie er behoben werden kann.

In der folgenden Tabelle werden die von erkannten Back-End-Konfigurationsfehler aufgeführt `storage errors show` und Sie werden auf detaillierte Informationen über die Ursachen und deren Auflösung hingewiesen.

|===
| `storage errors show` Nachricht | Weitere Informationen zu dieser Meldung finden Sie unter... 


 a| 
`NAME (Serial #): All paths to this array LUN are connected to the same fault domain. This is a single point of failure``.
 a| 
xref:reference_all_paths_to_an_array_lun_are_on_the_same_storage_array_controller.adoc[Alle Pfade zu einer Array-LUN befinden sich auf demselben Storage Array Controller]



 a| 
`NAME (Serial #), port WWPN1: LUN 1 occurs more than once. LUNs cannot be reused on the same array target port`.
 a| 
xref:reference_duplicate_lun_ids_on_a_target_port.adoc[Duplizierte LUN-IDs an einem Zielport]



 a| 
`NAME (Serial #): This array LUN is an access control LUN. It is not supported and should be masked off or disabled``.
 a| 
xref:reference_an_access_control_lun_is_presented_to_ontap.adoc[Access Control-LUN wurde präsentiert]



 a| 
`NAME (Serial #) This array LUN is configured with conflicting failover modes. Each path to this LUN must use the same mode`.
 a| 
xref:reference_array_luns_are_configured_with_conflicting_failover_modes_clustered_data_ontap_8_2_and_later.adoc[Array-LUNs werden mit widersprüchlichen Failover-Modi konfiguriert]



 a| 
`NAME (Serial #): This Array LUN is only available on one path. Proper configuration requires two paths`.
 a| 
xref:reference_fewer_than_two_paths_to_an_array_lun.adoc[Weniger als zwei Pfade zu einer Array-LUN]



 a| 
`NAME (Serial #): This array LUN is too large and is not usable. The maximum array LUN size supported is xTB`.
 a| 
xref:reference_array_lun_is_either_smaller_or_larger_than_the_supported_values.adoc[Array-LUN ist zu klein oder zu groß]



 a| 
`NAME (Serial #): This array LUN is too small and is not usable. The minimum array LUN size supported is 1GB`.
 a| 
xref:reference_array_lun_is_either_smaller_or_larger_than_the_supported_values.adoc[Array-LUN ist zu klein oder zu groß]



 a| 
`NAME (Serial #): This Array LUN is using multiple LUN IDs. Only one LUN ID per serial number is supported`.
 a| 
xref:reference_lun_ids_for_the_same_ldev_do_not_match.adoc[Die LUN-IDs für dasselbe LDEV stimmen nicht überein]

Die Adressierung des Volume-Satzes ist inkonsistent



 a| 
`NAME (Serial #): This array LUN is marked foreign and has a reservation`.
 a| 
xref:reference_array_lun_is_marked_foreign_and_has_a_reservation_data_ontap_8_3_and_later.adoc[Array-LUN ist als fremd markiert und hat eine Reservierung]

|===