---
permalink: install/task_verifying_if_the_back_end_configuration_matches_the_expected_output.html 
sidebar: sidebar 
keywords: verify, back-end, configuration, matches, intended, configuration 
summary: Nachdem Sie die durch Speicherfehler erkannten Back-End-Konfigurationsfehler behoben haben, müssen Sie prüfen, ob die vorhandene Back-End-Konfiguration mit der von Ihnen beabsichtigten Konfiguration übereinstimmt, und Probleme beheben, die sich aus Abweichungen ergeben. 
---
= Überprüfen, ob die Back-End-Konfiguration mit der beabsichtigten Konfiguration übereinstimmt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie die von erkannten Back-End-Konfigurationsfehler behoben haben, müssen Sie prüfen, ob die vorhandene Back-End-Konfiguration mit der von `storage errors show`Ihnen beabsichtigten Konfiguration übereinstimmt, und Probleme beheben, die sich aus einer Diskrepanz ergeben.

.Schritte
. Geben Sie den folgenden Befehl ein: `storage array config show`
+
Die `storage array config show` Ausgabe gruppiert Informationen über LUN-Gruppen, LUN-Anzahl und Pfade nach Storage Array. Wie im folgenden Beispiel für ein HA-Paar gezeigt wird:

+
[listing]
----

mysystem1::> storage array config show
             LUN   LUN
Node         Group Count  Array Name      Array Target Port   Initiator
------------ ----- ----- ---------------  ------------------  ---------
mysystem1a    0    10     DGC_RAID5_1      5005076303030124       1a
                                           5005076303088124       1b
                                           5005076303130124       1c
                                           5005076303188124       1d
mysystem1b    0    10     DGC_RAID5_1      5005076303030124       1a
                                           5005076303088124       1b
                                           5005076303130124       1c
                                           5005076303188124       1d
8 entries were displayed.
----
. Überprüfen Sie die `storage array config show` Ausgabe für jede Problembeschreibung in der folgenden Tabelle, und lesen Sie die entsprechenden Informationen zur Lösung.
+
|===
| Wenn Sie dieses Problem finden... | Siehe diese Informationen... 


 a| 
Leere LUN-Gruppen
 a| 
xref:reference_reasons_for_no_luns_in_the_array_lun_group.adoc[Gründe für keine LUNs in der Array-LUN-Gruppe]



 a| 
Erwartete Speicher-Arrays fehlen
 a| 
xref:reference_reasons_storage_arrays_are_missing_from_command_output.adoc[Gründe, warum möglicherweise nicht alle erwarteten Storage-Arrays angezeigt werden]



 a| 
Mehr Array-LUN-Gruppen als erwartet
 a| 
xref:reference_reasons_for_more_array_lun_groups_than_expected.adoc[Gründe für mehr Array-LUN-Gruppen als erwartet]



 a| 
Weniger Array-LUN-Gruppen als erwartet
 a| 
xref:reference_reasons_for_fewer_array_lun_groups_than_expected.adoc[Gründe für weniger Array-LUN-Gruppen als erwartet]



 a| 
Array-LUN-Gruppen zeigen nicht die Anzahl der erwarteten LUNs an
 a| 
xref:reference_reasons_for_the_incorrect_number_of_luns_in_array_lun_groups.adoc[Gründe für die falsche Anzahl von LUNs in Array-LUN-Gruppen]



 a| 
Weniger Pfade als erwartet
 a| 
xref:reference_fewer_than_two_paths_to_an_array_lun.adoc[Weniger als zwei Pfade zu einer Array-LUN]



 a| 
Mehr Pfade als erwartet
 a| 
xref:reference_reasons_for_more_paths_to_an_array_lun_than_expected.adoc[Gründe für mehr Pfade zu einer Array-LUN als erwartet]

|===

