---
permalink: install/task_preparing_a_storage_array_for_use_with_ontap_systems.html 
sidebar: sidebar 
keywords: prepare, storage, array, use, ontap, systems 
summary: Bevor Sie mit der Einrichtung von ONTAP-Systemen in einer Konfiguration mit Array-LUNs beginnen können, muss der Storage-Array-Administrator den Speicher für die Verwendung mit ONTAP vorbereiten. 
---
= Vorbereiten eines Speicher-Arrays für die Verwendung mit ONTAP-Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie mit der Einrichtung von ONTAP-Systemen in einer Konfiguration mit Array-LUNs beginnen können, muss der Storage-Array-Administrator den Speicher für die Verwendung mit ONTAP vorbereiten.

*Was Sie brauchen*

Die Speicher-Arrays, Firmware und Switches, die Sie in der Konfiguration verwenden möchten, müssen von der jeweiligen ONTAP Version unterstützt werden.

* https://mysupport.netapp.com/NOW/products/interoperability["NetApp Interoperabilität"]
+
Im IMT können Sie im Feld Storage-Lösung die Auswahl Ihrer MetroCluster Lösung verwenden. Sie verwenden den *Komponenten-Explorer*, um die Komponenten und die ONTAP-Version auszuwählen, um Ihre Suche zu verfeinern. Klicken Sie auf *Ergebnisse anzeigen*, um die Liste der unterstützten Konfigurationen anzuzeigen, die den Kriterien entsprechen.

* https://hwu.netapp.com["NetApp Hardware Universe"]


Sie müssen sich mit dem Storage Array-Administrator abstimmen, um diese Aufgabe auf dem Storage Array durchzuführen.

.Schritte
. Erstellen Sie mindestens vier LUNs auf dem Speicher-Array, die von den ONTAP-Systemen verwendet werden sollen.
+
Jeder Node im HA-Paar benötigt eine Array-LUN für das Root-Volume und eine Array-LUN für Core Dumps.

. Konfigurieren Sie Parameter auf dem Storage Array, die für die Nutzung mit ONTAP erforderlich sind.
+
** https://docs.netapp.com/us-en/ontap-flexarray/implement-third-party/index.html["FlexArray Virtualisierungs-Implementierung für Storage von Drittanbietern"]
** https://docs.netapp.com/us-en/ontap-flexarray/implement-e-series/index.html["FlexArray Virtualisierungs-Implementierung für NetApp E-Series Storage"]



