---
permalink: implement-third-party/concept_caution_about_using_the_vcmdb_lun.html 
sidebar: sidebar 
keywords: caution, using, vcmdb, lun 
summary: 'Damit die VCMDB (Volume Configuration Management Database) aktiviert werden kann, muss die VCMDB LUN vorhanden sein. Die VCMDB LUN ist ein Befehlstyp LUN, keine Storage-LUN. Die VCMDB ist normalerweise LUN 0 zugeordnet, kann aber einer anderen Array-LUN als LUN 0 zugeordnet werden.' 
---
= Vorsicht bei der Verwendung der VCMDB LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Damit die VCMDB (Volume Configuration Management Database) aktiviert werden kann, muss die VCMDB LUN vorhanden sein. Die VCMDB LUN ist eine `command` LUN vom Typ, keine Storage-LUN. Die VCMDB ist normalerweise LUN 0 zugeordnet, kann aber einer anderen Array-LUN als LUN 0 zugeordnet werden.

Wenn die VCMDB-LUN einem ONTAP-System zugeordnet ist, protokolliert ONTAP regelmäßig eine Meldung, dass die VCMDB-LUN kleiner als die erforderliche Mindestgröße ist, und markiert die VCMDB-LUN als fehlgeschlagen. Das ONTAP System funktioniert nach dem Protokollieren dieser Fehlermeldung weiterhin ordnungsgemäß, kann die LUN jedoch nicht verwenden.

Die Zuordnung einer VCMDB-LUN zu einem ONTAP-System sollte aufgehoben werden.
