---
permalink: implement-third-party/reference_workaround_when_luns_are_not_visible_with_hp_xp_storage_arrays.html 
sidebar: sidebar 
keywords: workaround, luns, not, visible, hp xp, storage, arrays, aggregates, created, ontap, system 
summary: Die im Abschnitt erforderliche Parameter für HP XP-Speicher-Arrays mit ONTAP-Systemen angegebenen Speicher-Array-Parameter sollten festgelegt werden und LUNs den Host-Gruppen zugeordnet werden, bevor der Switch in Zonen eingeteilt wird, um das ONTAP-System, das Array-LUNs verwendet, mit einem HP XP-Speicher-Array zu verbinden. 
---
= Problemumgehung, wenn LUNs bei HP XP-Speicherarrays nicht sichtbar sind
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die im Abschnitt erforderliche Parameter für HP XP-Speicher-Arrays mit ONTAP-Systemen angegebenen Speicher-Array-Parameter sollten festgelegt werden und LUNs den Host-Gruppen zugeordnet werden, bevor der Switch in Zonen eingeteilt wird, um das ONTAP-System, das Array-LUNs verwendet, mit einem HP XP-Speicher-Array zu verbinden.

xref:reference_required_parameters_for_hp_xp_storage_arrays_with_data_ontap_systems.adoc[Erforderliche Parameter für HP XP-Speicher-Arrays mit ONTAP-Systemen]

Wenn das Zoning vor dem Festlegen der Parameter und dem Zuordnen der LUNs zu den Host-Gruppen konfiguriert wurde, können Sie das Problem von LUNs beheben, die nicht sichtbar sind, indem Sie einen Pfad erneut initialisieren. Die Pfadneuinitialisierung erzwingt eine erneute Erkennung der Array-LUNs, die einem HP XP-Speicher-Array zugeordnet sind.

Das Verfahren, das Sie verwenden, hängt davon ab, ob Aggregate mit HP XP Array LUNs bereits auf dem ONTAP System konfiguriert wurden. (Bei den folgenden Verfahren wird davon ausgegangen, dass Knoten-1 und Knoten-2 die Namen der ONTAP-Nodes sind.)



== Wenn Aggregate mit HP XP Array LUNs bereits auf einem ONTAP System erstellt wurden, das Array LUNs verwendet

. Führen Sie den folgenden Befehl aus, um sicherzustellen, dass die HA-Konfiguration auf Ihren ONTAP Systemen aktiviert ist: *`cluster ha show`*
+
Die folgende Ausgabe wird angezeigt:

+
[listing]
----

High Availability Configured: true
----
. Führen Sie den folgenden Befehl aus, um sicherzustellen, dass Storage Failover auf Ihren ONTAP Systemen konfiguriert ist: *`storage failover show`*
+
Die folgende Ausgabe wird angezeigt:

+
[listing]
----
          Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
Node-1    Node-2    true     Connected to Node-2
Node-2    Node-1    true     Connected to Node-1
2 entries were displayed.
----
. Führen Sie einen Takeover-Vorgang auf Node-1 durch, indem Sie den folgenden Befehl ausführen: *`storage failover takeover -ofnode Node-1`*
. Führen Sie den folgenden Befehl erneut aus, um zu überprüfen, ob Node-2 für einen Giveback-Vorgang bereit ist: *`storage failover show`*
+
Die folgende Ausgabe wird angezeigt:

+
[listing]
----
          Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
Node-2    Node-1    false    In takeover, Auto giveback will be
                                      initiated in 348 seconds
Node-1    Node-2    -        Waiting for giveback (HA mailboxes)
2 entries were displayed.
----
. Führen Sie einen Giveback-Vorgang auf Node-1 durch, indem Sie den folgenden Befehl ausführen: *`storage failover giveback -ofnode Node-1 -require-partner-waiting true`*
. Wiederholen Sie von anderen Nodes im Cluster die Schritte 3 bis 5.




== Wenn Aggregate mit HP XP Array LUNs nicht auf einem ONTAP System erstellt wurden, das Array LUNs verwendet

. Führen Sie den folgenden Befehl aus, um alle ONTAP-FC-Initiator-Ports aufzulisten, die mit dem HP XP-Speicher-Array verbunden sind: *`system node run -node <node name> -command "sysconfig -v"`*
+
Beispiel: *`system node run -node Node-1 -command "sysconfig -v"`*

. Führen Sie den folgenden Befehl aus, um alle aufgeführten Ports offline zu schalten: *`system node run -node <node name> -command "priv set advanced;fcadmin offline <adapter>"`*
+
Beispiel: *`system node run -node Node-1 -command "priv set advanced;fcadmin offline 0a"`*

. Führen Sie den folgenden Befehl aus, um alle aufgeführten Ports online zu schalten: *`system node run -node <node name> -command "priv set advanced;fcadmin online <adapter>"`*
+
Beispiel: *`system node run -node Node-1 -command "priv set advanced;fcadmin online 0a"`*


